apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sxys3v9bf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sxys3v9bf-go 
  name: sxys3v9bf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sxys3v9bf-go 
