apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sxys3v9bf-go 
  janus-idp.io/tekton: sxys3v9bf-go
  backstage.io/kubernetes-id: sxys3v9bf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sxys3v9bf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml